import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// components/Layout.tsx or directly in your Login component
import "../../public/assets/css/bootstrap.min.css";
import "../../public/assets/css/common.css";
import "../../public/assets/css/main.css";
import "../../public/assets/css/responsive.css";

// import "./globals.css";
import LoadScripts from "@/components/LoadScripts";
import { Providers } from "@/components/Providers";
import SoonerClient from "@/components/SoonerClient";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SoonerClient />
        <LoadScripts />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
